name=Microlog
version=6.4.1
author=Andrei Gramakov <mail@agramakov.me>, rxi
maintainer=Andrei Gramakov <mail@agramakov.me>
sentence=A simple customizable logging library.
paragraph=Microlog is a lightweight and flexible logging library for C/C++ projects, now with Arduino support. It allows for easy integration of logging functionalities with various output targets, log levels, and customizable formatting.
category=Data Processing
url=https://github.com/an-dr/microlog
architectures=*
