// This file is automatically generated to force-link all functions in ulog.c for coverage
#include "ulog.h"
#include <stdio.h>
#include <stdbool.h>

void __force_link_all_ulog(void) {
    // Topics (if enabled)
#if FEATURE_TOPICS
    ulog_add_topic("force_topic", true);
    ulog_set_topic_level("force_topic", LOG_TRACE);
    ulog_enable_topic("force_topic");
    ulog_disable_topic("force_topic");
    ulog_enable_all_topics();
    ulog_disable_all_topics();
    ulog_get_topic_id("force_topic");
#endif
    // Extra outputs (if enabled)
#if FEATURE_EXTRA_OUTPUTS
    ulog_add_callback(NULL, NULL, LOG_TRACE);
    ulog_add_fp(NULL, LOG_TRACE);
#endif
#if FEATURE_CUSTOM_PREFIX
    ulog_set_prefix_fn(NULL);
#endif
    // Core
    ulog_set_lock(NULL, NULL);
    ulog_get_level_string(LOG_TRACE);
    ulog_set_level(LOG_TRACE);
    ulog_set_quiet(false);
    // Logging
    ulog_log(LOG_TRACE, __FILE__, __LINE__, NULL, "force log: %d", 42);
}