name: CMake Package

on:
  workflow_call:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run build script
        run: pwsh -File ./scripts/build_cmake.ps1

      - name: Read version and set artifact name
        run: echo "ARTIFACT_NAME=microlog-$(cat ./version)-cmake" >> $GITHUB_ENV

      - name: Upload CMake package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: install/cmake
