# Creates a GitHub Release and uploads artifacts from previous steps.
# Require artifacts:
# - env.ARTIFACT_CMAKE
# - env.ARTIFACT_MESON

name: Release

on:
  workflow_call:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build script
        run: pwsh -File ./scripts/build_cmake.ps1

      - name: Read version and set artifact name
        run: echo "ARTIFACT_CMAKE=microlog-$(cat ./version)-cmake" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          cd install/cmake
          zip -r ${{ env.ARTIFACT_CMAKE }}.zip .

      - name: Upload CMake package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_CMAKE }}
          path: install/cmake/${{ env.ARTIFACT_CMAKE }}.zip

  build-meson:
    runs-on: ubuntu-latest
    outputs:
      artifact-meson: ${{ steps.set-artifact-name.outputs.artifact_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Meson and Ninja
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build

      - name: Run build script
        run: pwsh -File ./scripts/build_meson.ps1

      - name: Set artifact name
        id: set-artifact-name
        run: echo "artifact_name=microlog-$(cat ./version)-meson" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          cd install/meson
          zip -r ${{ steps.set-artifact-name.outputs.artifact_name }}.zip .

      - name: Upload Meson package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact_name }}
          path: install/meson/${{ steps.set-artifact-name.outputs.artifact_name }}.zip

  build-src:
    runs-on: ubuntu-latest
    outputs:
      artifact-src: ${{ steps.set-artifact-name.outputs.artifact_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build script
        run: pwsh -File ./scripts/build_src.ps1

      - name: Set artifact name
        id: set-artifact-name
        run: echo "artifact_name=microlog-$(cat ./version)-src" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          cd install/src
          zip -r ${{ steps.set-artifact-name.outputs.artifact_name }}.zip .

      - name: Upload Source package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact_name }}
          path: install/src/${{ steps.set-artifact-name.outputs.artifact_name }}.zip


  release:
    runs-on: ubuntu-latest
    needs: [build-cmake, build-meson, build-src]
    outputs:
      artifact-cmake: ${{ needs.build-cmake.outputs.artifact-cmake }}
      artifact-meson: ${{ needs.build-meson.outputs.artifact-meson }}
      artifact-src: ${{ needs.build-src.outputs.artifact-src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CMake artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-cmake.outputs.artifact-cmake }}
          path: ./release-artifacts

      - name: Download Meson artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-meson.outputs.artifact-meson }}
          path: ./release-artifacts

      - name: Download Source artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-src.outputs.artifact-src }}
          path: ./release-artifacts

      # - name: Create GitHub Release and Upload Artifact
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ./release-artifacts/**
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
