# Creates a GitHub Release and uploads artifacts from previous steps.
# Require artifacts:
# - env.ARTIFACT_CMAKE
# - env.ARTIFACT_MESON

name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build-cmake, build-meson, build-src]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CMake artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-cmake.outputs.package-name }}
          path: ./release-artifacts

      - name: Download Meson artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-meson.outputs.package-name }}
          path: ./release-artifacts

      - name: Download Source artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-src.outputs.package-name }}
          path: ./release-artifacts

      # - name: Create GitHub Release and Upload Artifact
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ./release-artifacts/**
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
