name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CMake artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_CMAKE }}
          path: ./release-artifacts

      - name: Download Meson artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_MESON }}
          path: ./release-artifacts

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
