name: Version Change

on:
  push:
    paths:
      - version
    branches:
      - main

jobs:
  update-version:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Read version
          id: get_version
          run: echo "VERSION=v$(cat version)" >> "$GITHUB_ENV"

        - name: Replace version in source files
          run: |
            echo "Replacing version with $VERSION"
            find . -type f \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) \
              -exec sed -i -E "s/v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9._]+)?/$VERSION/g" {} +

        - name: Commit changes
          run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "Update source files version to $VERSION" || echo "No changes to commit"
            git push


  tag:
    needs: update-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        run: echo "VERSION=v$(cat version)" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Exiting."
            exit 0
          fi
        env:
          VERSION: ${{ steps.read_version.outputs.VERSION }}

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $VERSION
          git push origin $VERSION
        env:
          VERSION: ${{ steps.read_version.outputs.VERSION }}
