# Executes unit tests using CMake and PowerShell
name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on:
      ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.20.x"
          
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov
        
      - name: Test
        run: pwsh tests/unit/run_tests.ps1

      - name: Create archive of failed artifacts
        if: failure()
        run: |
          cd build_tests
          zip -r build_tests.zip .

      - name: Upload failed test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build_tests
          path: build_tests/build_tests.zip

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build_tests/coverage_report/
