# Executes unit tests using CMake and PowerShell
name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.20.x"

      - name: Test
        run: pwsh tests/unit/run_tests.ps1
        
      - name: Create archive
        if: ${{ always() }}
        run: |
          cd build_tests
          zip -r build_tests.zip .
          
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build_tests
          path: build_tests/build_tests.zip
