# Tests packages:
# - CMake
# - Meson

name: Integration Tests

on:
  workflow_call:

jobs:
  test-packaging:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout PR code
        # This is needed for testing the PR code. Github create a merge commit
        # that breaks the tests.
        uses: actions/checkout@v5
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          
      - name: Checkout Push code
        # This is needed for testing the main branch after a push
      - uses: actions/checkout@v5
        if: github.event_name == 'push'
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Install Meson and Ninja
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build

      - name: Test Meson Package
        run: pwsh -File ./tests/integration/packaging/test_meson.ps1

      - name: Test CMake Package
        run: pwsh -File ./tests/integration/packaging/test_cmake.ps1
        
      - name: Test CMake + CPM
        run: pwsh -File ./tests/integration/cpm/test_cpm.ps1

