# Tests packages:
# - CMake
# - Meson

name: Integration Tests

on:
  workflow_call:

jobs:
  test-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Meson and Ninja
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build

      - name: Test Meson Package
        run: pwsh -File ./tests/integration/packaging/test_meson.ps1

      - name: Test CMake Package
        run: pwsh -File ./tests/integration/packaging/test_cmake.ps1
        
      - name: Test CMake + CPM
        run: pwsh -File ./tests/integration/cpm/test_cpm.ps1

