# Executes UT and package tests

name: Tests

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/test-unit.yml
  
  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/test-integration.yml

    
