name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  verify-version:
    uses: ./.github/workflows/verify.yml

  build:
    uses: ./.github/workflows/build.yml

  test-packages:
    needs: build
    uses: ./.github/workflows/test-packages.yml

  test-unit:
    uses: ./.github/workflows/test-unit.yml
