# Checks whether the content is mergeable. Tests are run in a separate workflow.

name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  verify-version:
    uses: ./.github/workflows/verify-version.yml

