name: Merge Workflow

on:
  push:
    branches:
      - main

jobs:
  verify-version:
    uses: ./.github/workflows/verify.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test-packages.yml
